### ISSUE TITLE
Error in BepInEx

### ISSUE THREAD

**Issue by SGZ-Creations** [cmyager/EternalSolarSails#1]
Unsure if this would be a reason for it to not work. Tho i want to share this with you.
![image](https://github.com/cmyager/EternalSolarSails/assets/59801736/08807f6c-957c-4994-b05d-49f876fba2bb)

**Comment by cmyager** [comment]
Thanks! I've been waiting for some mods to get updated to pick up the game again, but I'll look into this today.

**Comment by cmyager** [comment]
I tried the following combinations on the most recent update (v0.10.28.21014) and the mod is working for me.

* BepInEx v5.4.17 and EternalSolarSails v1.0.0 installed via r2modman
* BepInEx v5.4.22 and EternalSolarSails v1.0.0 installed directly to the game folder

Can you give me some more info on your configuration?

* Game version
* BepInEx version
* How you are loading the mod?

**Comment by SGZ-Creations** [comment]
ok. Might be some i have done on my end, thanks. Sorry for the disturbance.
